### PR TITLE
Added option to disable use of https proxy in apt::ppa

### PR DESCRIPTION
**Pull request by Vincent--**
See https://tickets.puppetlabs.com/browse/MODULES-1831

### CODE REVIEW

**Comment by daenney** [comment]
Tests please, and docs, as explained in [CONTRIBUTING](https://github.com/puppetlabs/puppetlabs-apt/blob/master/CONTRIBUTING.md).

**Comment by mhaskel** [comment]
@Vincent-- this will also need a rebase now.

**Comment by daenney** [comment]
By the way, this feature is already implemented for Apt 2.0. Since 1.8 is on the verge of getting released it's unlikely this will make it in in time.

**Comment by mhaskel** [comment]
Thanks for the contribution @Vincent-- , but I'm closing this since apt 1.8.x was already released and it's already in the next branch.

**Pull request closed without merging**
