### PR TITLE
MODULES-2102 add proxy exception parameter

### PR DESCRIPTION
**Pull request by invertigo**
Extend the proxy.erb template to allow direct connections to specified apt repo hosts.

### CODE REVIEW

**Comment by daenney** [comment]
This broke all the existing tests for the proxy behaviour and misses tests that covers the new behaviour.

**Comment by invertigo** [comment]
Sorry about that!  I will get on fixing test coverage as I have a chance.

**Comment by daenney** [comment]
Any news on this?

**Comment by HelenCampbell** [comment]
Hi @invertigo, thanks for the work you have put in to this pull request. However due to inactivity and failing unit tests this pull request is being closed. If you want to re-submit this PR with the necessary changes, we will gladly look at the new pull request.

**Pull request closed without merging**
