### PR TITLE
(MODULES-9482) Bump translate dependency upper range

### PR DESCRIPTION
**Pull request by eimlav**

### CODE REVIEW

**Comment by ekohl** [comment]
Could this make it into a release? My acceptance tests are failing because puppetlabs-concat does allow a newer version. Then puppetlabs-apt is unhappy.

**Comment by eimlav** [comment]
Hi @ekohl . We will get a release out this week. Cheers!

**Comment by ekohl** [comment]
@eimlav do you have any ETA? I'm wondering if I should be implementing workarounds in modules

**Comment by eimlav** [comment]
Hi @ekohl v7.1.0 has now been released. I hope this helps with your issues!

**Pull request merged**
