### PR TITLE
Change to stop apt-get update being considered a 'change' in a puppet run.

### PR DESCRIPTION
**Pull request by aug24**
https://jira.puppetlabs.com/browse/PUP-4498

### CODE REVIEW

**Comment by daenney** [comment]
Can someone elaborate a bit more on the ticket, the cause and how this solves it? I'm having a hard time understanding what this will fix.

**Comment by daenney** [comment]
The test failure is related to a previous merge, I'll have a look at that.

**Comment by aug24** [comment]
I was just getting round to elaborating, I got sidetracked trying to understand the test failure....

**Comment by aug24** [comment]
Elaboration added: https://jira.puppetlabs.com/browse/PUP-4498

**Comment by tphoney** [comment]
@aug24 Based on the jira ticket you are looking into an alternate implementation. If so can you close the ticket ?

**Comment by tphoney** [comment]
@aug24 closing due to inactivity and the work that has went into https://tickets.puppetlabs.com/browse/PUP-4498

**Pull request closed without merging**
