### PR TITLE
[MODULES-9695] - Add support for signed-by in source entries

### PR DESCRIPTION
**Pull request by johanfleury**
This is a first step toward fixing [MODULES-9695](https://tickets.puppetlabs.com/browse/MODULES-9695).

I refactored the option list as an hash, as per [Antoine’s comment](https://tickets.puppetlabs.com/browse/MODULES-9695?focusedCommentId=719431&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-719431).

### CODE REVIEW

**Comment by daianamezdrea** [comment]
Hi @johanfleury, is this still WIP ?

**Comment by johanfleury** [comment]
Nope, I believe it’s ready to review.

Do you need me to test this in an actual code base (I didn’t have time this week-end, but I can do it today)?

**Comment by johanfleury** [comment]
I tested on my own infra and it works as expected.

Just a few remarks regarding this PR:
* I named the parameter `$keyring` and not `$signed_by` because I think it could later be used to manage the actual keyring file (see my comment on MODULES-9695).
* I think, it could be a good idea instead of having every options as parameters, to have a single `$options` hash as there are [a **lot** of options](https://manpages.debian.org/unstable/apt/sources.list.5.en.html#THE_DEB_AND_DEB-SRC_TYPES:_OPTIONS) that this module doesn’t currently support.
* Some options (`signed-by` included) allow multiple, comma separated, values (see [the sources.list man page](https://manpages.debian.org/unstable/apt/sources.list.5.en.html#ONE-LINE-STYLE_FORMAT)), it could be a good idea to allow passing `$keyring` as an Array instead of a single string.

What do you think?

**Review by kenyon — APPROVED** [review]

**Comment by daianamezdrea** [comment]
Hi @johanfleury, it looks good for me, thank you for your contribution ! Cheers !

**Comment by daianamezdrea** [comment]
I also looked at your comments from the PR and the ones from the ticket, I'm waiting for your new PR/PRs. Just let me know if you need help/review. Thank you again !

**Review by daianamezdrea — APPROVED** [review]

**Comment by vegaaz** [comment]
This PR fixed the [MODULES-9695](https://tickets.puppetlabs.com/browse/MODULES-9695) Issue.
Since the issue is still 'Open' some people have no idea this was fixxed.

Can someone with a tickets.puppetlabs.com-Account close the issue?

**Comment by johanfleury** [comment]
@vegaaz I don’t think this PR fixes MODULE-9695, it merely adds support for a new flag in `sources.list` files, but there’s still a lot of work to do to remove calls to `apt-key`. See [my comment on the issue](https://tickets.puppetlabs.com/browse/MODULES-9695?focusedCommentId=812916#comment-812916).

**Pull request merged**
