### PR TITLE
Add a facter fact for dist-upgrade

### PR DESCRIPTION
**Pull request by willmeek**
This commit adds a facter fact for dist-upgrade, along with
associated facter facts.

(Builds upon PR https://github.com/puppetlabs/puppetlabs-apt/pull/634 - adds a new set of facts to maintain compatibility)

### CODE REVIEW

**Comment by eputnam** [comment]
i took a peek at tests. may have something to do with scoping in RSpec. while i was testing apt_dist_has_updates_spec.rb, the fact was returning `nil`, not even false for the last example but putting `File.expects(:executable?).with('/usr/bin/apt-get').returns true` in the actual example (instead of the before block), it seemed to help a little.

**Comment by willmeek** [comment]
@eputnam I can't replicate this, if I add the expect outside of the block then it returns nil, the opposite of what you are seeing. Travis has gone green too. Let's discuss this later.

**Comment by willmeek** [comment]
Facts in readme updated, thanks

**Comment by willmeek** [comment]
Thanks @eputnam

**Pull request merged**
