### PR TITLE
MODULES-1661 Fix to do delete with short key not long

### PR DESCRIPTION
**Pull request by cyberious**

### CODE REVIEW

**Comment by WolverineFan** [comment]
Why would you want to use the short key to delete?  If the short key isn't unique, you could potentially delete the wrong key (for example the puppetlabs key).  Honestly since you're using the provider, why not just delete using the fingerprint?  That's guaranteed to be unique.

**Comment by WolverineFan** [comment]
Nevermind, I see it.  Looks like the ensure absent stuff needs refactoring too.  What you're doing here is trying to hack around the short key not being unique problem by deleting all the "duplicates" (which are actually different keys with the same short signature).  That's going to cause issues on other fronts.  But it's the old behavior so at least this is more expected until it can be fixed for real.

**Comment by cyberious** [comment]
The problem was also that we were trying to delete by the id, which if passed as a long has a bug that won't delete the key.  If fingerprint will delete the key will all versions of apt-key I am in favor of that for a future PR.

**Comment by cyberious** [comment]
@WolverineFan I created PR #410 with the changes to fingerprint instead.  Same recursive behavior

**Pull request merged**
