### PR TITLE
It's been a long time - how have you been

### PR DESCRIPTION
**Pull request by daenney**
A set of commits changing a lot of behaviour of apt for the better. I can't do this as separate PR's as some of them depend on each other which would really slow down the process.

For review purposes I suggest having a look at each individual commit or brains might melt.

glados

### CODE REVIEW

**Comment by daenney** [comment]
I have not yet had the time to look at the Beaker tests. I expect them to explode phenomenally.

**Comment by mhaskel** [comment]
urgh, sorry, reviewing commit by commit made the inline comments look less readable in the PR :\

**Comment by daenney** [comment]
The last two commits ought to have come before my commit that does changes to `apt::source` but unfortunately I can't rewrite that part of history. It gets messy so the commits are slightly out of order, sorry.

**Comment by mhaskel** [comment]
Looks good, thanks @daenney 

Also, I really like what github did apt::key: in your commit messages.

**Pull request merged**
