### PR TITLE
(GH-cat-9) Update module to match current syntax standard

### PR DESCRIPTION
**Pull request by david22swan**
Module is now in compliance with the following rules:
- optional_default
- strict_indent
- unquoted_string_in_case
- parameter_documentation
- relative_classname_inclusion
- no-top_scope_facts-check
- no-top_scope_variable-check
- variable_scope

The below exception has been left in place:
- disable_anchor_resource

### CODE REVIEW

**Review by GSPatton — APPROVED** [review]
all looks good to me

**Review by chelnak — APPROVED** [review]
LGTM 👍

**Comment by jensk** [comment]
This changeset introduces a warning which breaks an important part of the update manifest

````
Warning: Unknown variable: 'apt::apt_update_last_success'. (file: /usr/local/puppet/vendor/apt/manifests/update.pp, line: 22, column: 12)
````

**Comment by kenyon** [comment]
@jensk that should have been fixed in #1081.

**Pull request merged**
