### PR TITLE
(maint) Set DEBIAN_FRONTEND=noninteractive on upgrade

### PR DESCRIPTION
**Pull request by smortex**
When upgrading Debian packages, the system sometimes what to prompt the user about what action to perform.  Since a tasks is supposed to be non-interactive, we should disable such prompts.

This help when updating some packages, e.g. postfix.

### CODE REVIEW

**Comment by smortex** [comment]
I also think that we should explicitly add `-o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"` to the command line.

Though?

**Comment by daianamezdrea** [comment]
Hi @smortex, the PR looks good and I'm planning to merge it, regarding your second comment, this should be solved by the "--force-yes" option

**Review by daianamezdrea — DISMISSED** [review]

**Comment by smortex** [comment]
Hi @daianamezdrea.  I just discussed the topic with a friend: `--force-yes` seems to be deprecated: it is not documented in recent versions of dpkg(1).  He confirmed `--force-confdef` and `--force-confold` are the way to go:

* If a configuration file shipped by an older package has not been modified, it is probably not managed by Puppet and it makes sense to continue to use the (updated) default configuration which ship with the updated package;
* If a configuration file shipped by an older package has been modified, it may be managed by Puppet which will revert any change, or not be managed by Puppet and the user probably does not want to loose her configuration.

**Comment by daianamezdrea** [comment]
Hello @smortex, I did a research also and I think you're right

**Comment by daianamezdrea** [comment]
Thank you for this PR and your contributions !

**Review by daianamezdrea — APPROVED** [review]

**Pull request merged**
