### PR TITLE
[DO NOT MERGE] "exercise ci"

### PR DESCRIPTION
**Pull request by nibalizer**

### CODE REVIEW

**Comment by mhaskel** [comment]
ci is very sad right now, so closing.

**Comment by hunner** [comment]
Reopening to see if CI gets happier.

**Comment by hunner** [comment]
Requested to leave open for future pokings

**Comment by nibalizer** [comment]
Not entirely sure what the problem is right now, closing this.

**Comment by daenney** [comment]
Ehm pepole, WTF is going on?

**Comment by nibalizer** [comment]
@daenney if you look at the CI report for this, pcci now votes with a green check

**Comment by nibalizer** [comment]
Although hillariously, closing the PR removes the CI information

**Comment by daenney** [comment]
@nibalizer Aaaah.

**Pull request closed without merging**
