### PR TITLE
Allow ports that consist of 5 decimals

### PR DESCRIPTION
**Pull request by voidus**

### CODE REVIEW

**Comment by voidus** [comment]
I'm having problems running the beaker tests. This happens both with puppetlabs/master as well as voidus/master. Are the beaker tests currently functional? If yes, it would be great if you could take a look at the error I'm getting[1] and tell me if you see something.

I already tried to look into it myself, but I couldn't find anything in the puppetlabs-spec docu or through google.

[1] http://pastebin.com/UkngEuzn

**Comment by daenney** [comment]
Right now I'm okay with ignoring the Beaker tests, at @mhaskel's discretion. I think we settled a while ago on not bugging the community about Beaker specs until we have a good way to run and visualise them for you without contributors needing to jump through fiery hoops of doom to get stuff running locally.

**Comment by mhaskel** [comment]
@voidus @daenney I'm ok just having unit tests for this feature.
To run the beaker-rspec tests we actually don't run them through rake, but they can be executed using `bundle exec rspec spec/acceptance`. More information can be found at https://github.com/puppetlabs/beaker/wiki/How-to-Write-a-Beaker-Test-for-a-Module

To get this ready for merge though can you rebase and squash it down to a single commit?

**Comment by voidus** [comment]
Done. Running the beaker tests through `bundle exec rspec rspec/acceptance` gives me the same error as `rake beaker`, though.

**Comment by daenney** [comment]
Thank you! We'll see about sorting out the beaker stuff.

**Pull request merged**
