### PR TITLE
(FM-7318) - Added Puppet Strings formatting to documentation

### PR DESCRIPTION
**Pull request by eimlav**

### CODE REVIEW

**Comment by eimlav** [comment]
- In Puppet Strings generated file REFERENCE.md table of contents, the link to resource type apt_key directs to the apt::key defined type section instead of to apt_key's appropriate section. 
- Files which have extensive summarys require more than 140 characters. This requires using the \@note tag for the rest of the summary information. Is there a better practice for going about this?

**Comment by eputnam** [comment]
@eimlav looks like you've resolved these issues? It could also be argued that the apt_key type is part of the module's private api, which would take it out of the equation completely in case fixing the link required a manual change.

**Comment by eimlav** [comment]
@eputnam The apt_key anchor link issue appears to have just been a problem with my IDE that I've just noticed when I used the REFERENCE.md file in GitHub. I have modified apt_key to be private now as you have suggested which prevents it from being rendered into REFERENCE.md. Thanks for the help!

**Comment by HelenCampbell** [comment]
Looks good!

**Comment by kenyon** [comment]
This change messed up the documentation. If you look at https://forge.puppet.com/puppetlabs/apt/types now, it's not being rendered correctly. Documentation on the Apt::Proxy type is missing too, for example.

**Comment by eimlav** [comment]
Hi @kenyon. The types section for a module on the Forge is used for displaying documentation of [resource types](https://puppet.com/docs/puppet/6.0/type.html) found in the [lib](https://github.com/puppetlabs/puppetlabs-apt/tree/master/lib) folder. Apt::Proxy on the other hand is a [type alias](https://puppet.com/docs/puppet/6.0/lang_type_aliases.html) from the [types](https://github.com/puppetlabs/puppetlabs-apt/tree/master/types) folder. The naming conventions are a little confusing but this is why it isn't in the types section on the Forge since this is for resource types. Unfortunately, type aliases also cannot be parsed by Puppet Strings yet so they are not present in the [REFERENCE.md](https://github.com/puppetlabs/puppetlabs-apt/tree/master/REFERENCE.md), however as soon as this feature is available we will be sure to implement it. I hope this helps clarify things for you :)

**Comment by kenyon** [comment]
OK, so why would you make it impossible to read the documentation without looking at the source? Not user-friendly.

Also, this change still messed up the rendering on the types page as mentioned.

**Pull request merged**
