### PR TITLE
Clear up lsb-release error

### PR DESCRIPTION
**Pull request by daenney**

### CODE REVIEW

**Comment by mhaskel** [comment]
Thanks for the clarification @daenney. @psoloway is working on a README update right now though, so I'm going to hold off on this until that's done just to avoid merge conflicts!

**Comment by daenney** [comment]
Alright. Ping me when that's done so I can rebase.

**Comment by mhaskel** [comment]
@daenney once #515 is merged this should be good to rebase, thanks :)

**Comment by mhaskel** [comment]
thanks @daenney !

**Pull request merged**
