### PR TITLE
(maint) Update the gpg key

### PR DESCRIPTION
**Pull request by underscorgan**
We're moving to a new gpg key! The old puppetlabs key was hardcoded in a few places (docs, test only). This updates to use the new short key/long key/fingerprint in all of those places.

### CODE REVIEW

**Comment by daenney** [comment]
There's a few Beaker tests that fail now, for example:

```
debian-8-x64 01:04:13$ puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.PjSNLF
  Info: Loading facts
  Info: Loading facts
  Notice: Compiled catalog for debian-8-x64.c.travis-ci-prod-4.internal in environment production in 0.12 seconds
  Info: Applying configuration version '1473987856'
  Error: The id in your manifest 6F6B15509CF8E59E6E469F327F438280EF8D349F and the fingerprint from content/source do not match. Please check there is not an error in the id or check the content/source is legitimate.
  Error: /Stage[main]/Main/Apt_key[puppetlabs]/ensure: change from absent to present failed: The id in your manifest 6F6B15509CF8E59E6E469F327F438280EF8D349F and the fingerprint from content/source do not match. Please check there is not an error in the id or check the content/source is legitimate.
  Notice: Applied catalog in 0.16 seconds
debian-8-x64 executed in 3.28 seconds
Exited: 4
      works (FAILED - 1)
    multiple keys
```

**Comment by underscorgan** [comment]
Thanks @daenney , taking a look

**Comment by underscorgan** [comment]
ok, I fixed some of the issues, not sure how this change could've broken the three failures I'm seeing now :|

```
  1) apt_key source => ftp:// fails with a 550
     Failure/Error:
       apply_manifest(pp, :expect_failures => true) do |r|
         expect(r.stderr).to match(/550 Failed to open/)
       end
     Beaker::Host::CommandFailure:
       Host 'debian-8-x64' exited with 0 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.Gj3cI7
       Last 200 lines of output were:
       	Info: Loading facts
       	Info: Loading facts
       	Notice: Compiled catalog for debian-8-x64.c.travis-ci-prod-2.internal in environment production in 0.10 seconds
       	Warning: /Apt_key[CentOS 6]: The id should be a full fingerprint (40 characters), see README.
       	Info: Applying configuration version '1474050519'
       	Notice: Applied catalog in 0.15 seconds
       
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/host.rb:351:in `exec'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/shared/host_manager.rb:127:in `run_block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/puppet_helpers.rb:480:in `block in apply_manifest_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/shared/host_manager.rb:127:in `run_block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/puppet_helpers.rb:409:in `apply_manifest_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/puppet_helpers.rb:487:in `apply_manifest'
     # ./spec/acceptance/apt_key_provider_spec.rb:614:in `block (4 levels) in <top (required)>'
  2) apt_key source => https:// fails with a 404
     Failure/Error:
       apply_manifest(pp, :expect_failures => true) do |r|
         expect(r.stderr).to match(/404 Not Found/)
       end
     Beaker::Host::CommandFailure:
       Host 'debian-8-x64' exited with 0 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.UJAtCJ
       Last 200 lines of output were:
       	Info: Loading facts
       	Info: Loading facts
       	Notice: Compiled catalog for debian-8-x64.c.travis-ci-prod-2.internal in environment production in 0.10 seconds
       	Warning: /Apt_key[puppetlabs]: The id should be a full fingerprint (40 characters), see README.
       	Info: Applying configuration version '1474050533'
       	Notice: Applied catalog in 0.15 seconds
       
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/host.rb:351:in `exec'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/shared/host_manager.rb:127:in `run_block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/puppet_helpers.rb:480:in `block in apply_manifest_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/shared/host_manager.rb:127:in `run_block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/puppet_helpers.rb:409:in `apply_manifest_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/puppet_helpers.rb:487:in `apply_manifest'
     # ./spec/acceptance/apt_key_provider_spec.rb:658:in `block (4 levels) in <top (required)>'
  3) apt_key source => https:// fails with a socket error
     Failure/Error:
       apply_manifest(pp, :expect_failures => true) do |r|
         expect(r.stderr).to match(/could not resolve/)
       end
     Beaker::Host::CommandFailure:
       Host 'debian-8-x64' exited with 0 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.emehgQ
       Last 200 lines of output were:
       	Info: Loading facts
       	Info: Loading facts
       	Notice: Compiled catalog for debian-8-x64.c.travis-ci-prod-2.internal in environment production in 0.11 seconds
       	Warning: /Apt_key[puppetlabs]: The id should be a full fingerprint (40 characters), see README.
       	Info: Applying configuration version '1474050536'
       	Notice: Applied catalog in 0.14 seconds
       
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/host.rb:351:in `exec'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/shared/host_manager.rb:127:in `run_block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/puppet_helpers.rb:480:in `block in apply_manifest_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/shared/host_manager.rb:127:in `run_block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/puppet_helpers.rb:409:in `apply_manifest_on'
     # ./vendor/bundle/ruby/2.3.0/gems/beaker-2.51.0/lib/beaker/dsl/helpers/puppet_helpers.rb:487:in `apply_manifest'
     # ./spec/acceptance/apt_key_provider_spec.rb:672:in `block (4 levels) in <top (required)>'
Finished in 4 minutes 34 seconds (files took 1 minute 11.55 seconds to load)
42 examples, 3 failures
Failed examples:
rspec ./spec/acceptance/apt_key_provider_spec.rb:605 # apt_key source => ftp:// fails with a 550
rspec ./spec/acceptance/apt_key_provider_spec.rb:649 # apt_key source => https:// fails with a 404
rspec ./spec/acceptance/apt_key_provider_spec.rb:663 # apt_key source => https:// fails with a socket error
```

**Comment by daenney** [comment]
Not a clue either. They're related to trying to trigger network errors though.

**Comment by underscorgan** [comment]
woop, missed one case for key replacement which meant the deletes weren't working right. working now :D

**Comment by daenney** [comment]
Awesome and nice catch 😄

**Pull request merged**
