### PR TITLE
Parametrize file permissions

### PR DESCRIPTION
**Pull request by carabasdaniel**
Possible alternative to: https://github.com/puppetlabs/puppetlabs-apt/pull/920

### CODE REVIEW

**Comment by carabasdaniel** [comment]
Hi @anarcat,

As we reverted file permissions in version 7.4.1 of the puppetlabs-apt module, I would like to know what is your opinion on exposing these values as parameters ?

**Comment by anarcat** [comment]
> As we reverted file permissions in version 7.4.1 of the puppetlabs-apt module, I would like to know what is your opinion on exposing these values as parameters ?

Thanks for working on this, Daniel, and sorry my patch was badly received by some members of the community.

Seems like making those a parameter is a fine idea. Maybe we could just completely drop the `mode` parameter of those incantations? That way the proper defaults would play out, and site-specific `File` blocks would apply.

It seems to me that adding an extra parameter wouldn't be worth the trouble.

**Comment by anarcat** [comment]
@carabasdaniel i made #923 to show what i mean.

**Comment by carabasdaniel** [comment]
Closed this as #923 was merged

**Pull request closed without merging**
