### PR TITLE
Purge apt::pin when apt::source is to be purged

### PR DESCRIPTION
**Pull request by raoulbhatia**

### CODE REVIEW

**Comment by mhaskel** [comment]
@raoulbhatia I still don't think this is going to work. You're only getting into the code block you added if `$pin = false`, so you'll end up passing `priority => false` to the `apt::pin` resource.

**Comment by raoulbhatia** [comment]
So what would the correct take on that be?

**Comment by raoulbhatia** [comment]
I have updated my patch to the recent git revision and have added a test to source_spec.rb.

I cannot see that the pin filename references the priority anywhere, at least not in puppetlabs-apt from git.

@daenney Could it be that this is an old assumption obsolete now and we would be good to go regarding this merge request?

**Comment by mhaskel** [comment]
Hi @raoulbhatia, thanks for the contribution but this PR is going to break the existing `backports` implementation from #398, and changes default behavior which could be very dangerous. In general we don't like the use of `if ! defined()` because that means that catalog compilation can be nondeterministic (with the backports example, you could either end up with the pin `ensure => present` or `ensure => absent`). As such, I'm going to close this PR, the best work-around would be to specify the pins you want to have removed in your node manifest or local roles/profiles. Thanks again.

**Pull request closed without merging**
