### PR TITLE
Introduce an Apt::Proxy type to validate the hash

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by pmcmaw** [comment]
Hey @ekohl 

Would it be possible to add some tests and documentation around this new functionality and I will work on getting it merged. 

:-)

**Comment by ekohl** [comment]
https://github.com/puppetlabs/puppetlabs-apt/blob/bdc285a725497e0e0215cdfcea1deca9c8a51b9d/spec/classes/apt_spec.rb#L80-L156 already has positive tests. I was sort of trusting the Puppet type system here but I could add a negative test if desired.

Note that the same pattern of verifying hashes is used in a lot of places in this module so there's a lot more that could be replaced in the same way but I didn't have time for that.

**Comment by pmcmaw** [comment]
Nope testing wise thats fine @ekohl I think thats fair.
Would it be possible to add a small README entry under the defined types section.

Also thanks for the quick response! :-)

**Comment by david22swan** [comment]
Have updated the readme to get this merged

**Comment by ekohl** [comment]
Thanks @david22swan. This sort of dropped of my radar for a bit. I must say I really like the Puppet 4 type system. Powerful yet straight forward to use.

**Comment by HelenCampbell** [comment]
Thank for your contribution @ekohl ! The Puppet 4 type system is awesome :D

**Pull request merged**
