### PR TITLE
Add support for calling `apt::update` directly

### PR DESCRIPTION
**Pull request by guessi**
eliminate the error message of variable look up failure:
- Could not look up qualified variable '::apt::always_apt_update'; class apt has not been evaluated
- Could not look up qualified variable 'apt::update_timeout'; class apt has not been evaluated
- Could not look up qualified variable 'apt::update_tries'; class apt has not been evaluated

### CODE REVIEW

**Comment by daenney** [comment]
Why? Why would you ever call `apt::update` directly and not have `apt` in your catalog too?

**Comment by guessi** [comment]
actually, I'm working on another project `puppetlabs-openstack`, and I found there's a error message in syslog, introduced by `openstack::resources::repo::uca`, line 7, since it doesn't have `apt` included, and yes, it can be fixed by modifying the code inside `uca.pp` but I think if it could be invoke via `apt::update` directly without knowing the whole `apt` project, that would be eaiser for users, that's why I create this pull request : )

ref: https://github.com/puppetlabs/puppetlabs-openstack/blob/master/manifests/resources/repo/uca.pp#L7

**Comment by daenney** [comment]
Using parts of `apt` without including the actual `apt` base class is going to keep giving issues in different places.

We also have the following line in our README in the Usage section:

> This module provides common resources and options that are shared by the various defined types in the apt module, so you **must** always include this class in your manifests.

It doesn't specifically mention other classes but I'm inclined to say no because of it. Since it doesn't hurt to include that same class multiple times I see less of a reason to accept this change.

However, I'd like @mhaskel to chime in on this.

**Comment by mhaskel** [comment]
@guessi I agree with @daenney on this one. You could end up with all sorts of weird issues using pieces of the `apt` module without `apt` itself. Thank you very much for the contribution, but since `apt` needs to be included to use other pieces of this module I'm going to close this PR.

**Comment by guessi** [comment]
got it, thanks for your reply, let's end this topic :+1:

**Pull request closed without merging**
