### PR TITLE
(MODULES-3307) - Auto update expired keys

### PR DESCRIPTION
**Pull request by eimlav**
Feature based on https://github.com/hbog/puppetlabs-apt/tree/refresh

### CODE REVIEW

**Comment by tphoney** [comment]
👍  assuming it can run through our adhoc pipeline

**Comment by eimlav** [comment]
Ran most recent commit bb0f842dc969cc71ca943a40345966dfc507edf2 through adhoc pipeline, and it has now gone green. 

screen shot 2018-09-21 at 09 01 04

**Comment by pmcmaw** [comment]
LGTM. Merging.

**Comment by anarcat** [comment]
this is a really bad idea, i must say. especially now that some people figured out that you can just flood any PGP key out there, fetching arbitrary keys from keyservers, *by default*, when *checking for existence of the key*, seems like a huge security problem.

it will necessarily lead to keys being poisoned and completely disabling the AptSecure key verification mechanism, possibly leading to DOS on the entire server as `apt` struggles to run at all.

key updates should be shipped in-band, as a *local* `source` parameter (as in `puppet://`) and that's it. i understand why someone would make the mistake of pulling from keyservers, because `apt-key adv` exists, but it's not a good idea to set things up that way.

more information on how to properly setup third-part repositories is available here, i strongly suggest this is taken into consideration in this module more broadly:

https://wiki.debian.org/DebianRepository/UseThirdParty

**Comment by lelutin** [comment]
I do concur with @anarcat 's analysis of this code. it seems to me to be a pretty bad idea (in general) to automatically download keys from keyservers, especially nowadays since the state of the keyservers is in such a bad shape.

I would be more comfortable with this module if this new code was deactivated by default

**Pull request merged**
