### PR TITLE
(FM-4049) update to modulesync_configs

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Comment by daenney** [comment]
Even more CI failing @DavidS. Is this a dupe of #4046?

**Comment by DavidS** [comment]
https://tickets.puppetlabs.com/browse/PUP-5743 is currently impacting
everything.

**Comment by daenney** [comment]
Oh boy...

**Comment by daenney** [comment]
`gem 'master_manipulator` :joy: :joy: :joy:

**Pull request merged**
