### PR TITLE
Add parameters for hiera merge

### PR DESCRIPTION
**Pull request by anders-larsson**
Add hiera merge functionality for sources, keys, ppas, pins and settings.
When hiera_merge parameter is set to true the corresponding parameters' value will be merged from from all hiera levels.

### CODE REVIEW

**Comment by daenney** [comment]
You can already solve this for yourself by installing the `deep_merge` gem and configuring Hiera accordingly. I don't think we should add this as a feature like this.

**Comment by daenney** [comment]
@bmjen thoughts?

**Comment by anders-larsson** [comment]
Using deep_merge would force merge all data from hiera always I think?
This is not always wanted. Sometimes you might want to disable hiera merging on specific systems/profiles and replace it with a completely different set of configuration. This pull request allows you do activate hiera parameter merging per default but disable it for specific systems.

**Comment by daenney** [comment]
If you want that kind of granularity you should wrap a profile around it that does the right thing in your case and passes the parameters in explicitly. Exposing it like this adds a lot of code that so far no one has asked for/needed and a lot of noise for something that's already easily solved through the usual patterns.

**Comment by anders-larsson** [comment]
Would you please inform me what "profile" means in this case? I suppose we're talking about manifests "profiles"? Not everyone uses that. Some of us only include classes in site.pp (using hiera_include('classes') and some other fixes that cannot be placed in hiera. All other configuration is made in hiera.

The preferred way in your opinion would be create a completely separated module adding this functionality? Having Hiera support but not merge support kind of defeats the purpose in my opinion of having hiera support at all.

**Comment by daenney** [comment]
> Would you please inform me what "profile" means in this case? I suppose we're talking about manifests "profiles"? Not everyone uses that.

Though that might be true, we can't cater to every possible use case that people come up with. We end up needing to maintain all that code and sorting out all the bugs that potentially come our way.

> The preferred way in your opinion would be create a completely separated module adding this functionality?

Yes. It doesn't have to be much more than:

```puppet
class profile::apt
  $source_hiera_merge = hiera('apt_source_merge')
  if $source_hiera_merge {

    class { 'apt':
      sources => hiera_merge('apt_sources'),
  }
}
``` 

> Having Hiera support but not merge support kind of defeats the purpose in my opinion of having hiera support at all.

Not really, you can still do a whole bunch of configuration of this module through Hiera, your sources and what not. We just can't cater for every possible way people want to wrangle data. The fact that you want to enable/disable it for specific systems is business logic. Business logic has no place in a generic/building block kind of module. That's not the right place for these things.

**Comment by bmjen** [comment]
I'm in agreement with @daenney on this one. I don't think this functionality should go into the module itself, especially since the usecase can be solved by wrapping the apt class as daenney has suggested above.

We appreciate the contribution @anders-larsson, but at this time it is not something we want to bring into the module.

**Comment by anders-larsson** [comment]
Thanks for the feedback @bmjen and @daenney!

**Comment by rnelson0** [comment]
@anders-larsson re: concerns about hiera deep merge and other lookups. You should instead look at the `lookup` function, which offers more granular control over merge behaviors. https://docs.puppetlabs.com/puppet/latest/reference/lookup_quick.html

**Pull request closed without merging**
