### PR TITLE
Allow weak SSL verification for apt_key

### PR DESCRIPTION
**Pull request by tuxmea**
fixes https://tickets.puppetlabs.com/browse/MODULES-8759

### CODE REVIEW

**Comment by eimlav** [comment]
Adhoc ran successfully so I'm going to go ahead and merge. Thanks for contributing @tuxmea  :)

Screen Shot 2019-03-20 at 13 39 51

**Comment by kenyon** [comment]
This change causes "Error: no parameter named 'weak_ssl'": https://tickets.puppetlabs.com/browse/MODULES-9209

**Comment by tuxmea** [comment]
> This change causes "Error: no parameter named 'weak_ssl'": https://tickets.puppetlabs.com/browse/MODULES-9209

This could be related to environment leaking when having two environments with different versions of a type/provider:
https://puppet.com/docs/puppet/5.3/environments_about.html#troubleshooting-environment-leaks

Are you running puppet generate types after r10k deployment?

**Comment by kenyon** [comment]
It seems that simply restarting puppetserver after upgrading modules fixed it. I guess that is standard procedure.

**Pull request merged**
