### PR TITLE
Use modern os facts

### PR DESCRIPTION
**Pull request by kenyon**
This turned into a bigger change than I originally imagined...

Background: I'm developing a module using PDK and Litmus. My module has an option to use the backport version of the Debian package. During acceptance testing with the `litmusimage/debian:10` Docker image, I found that a simple `include apt::backports` failed because `puppetlabs-apt` thought it wasn't running on Debian. This turned out to be because the `lsb-release` package wasn't installed. I noticed that, with Puppet 7 and Facter 4.0.47 anyway, the legacy OS facts aren't populated unless `lsb-release` is installed. However, the modern `os` fact structure is populated even without `lsb-release`. So rather than have my module ensure `lsb-release` is installed, I decided to update `puppetlabs-apt`, and this pull request is the result.

~Removing this package dependency makes the module more robust and simpler to use.~

Update: I see now that only Puppet 7 resolves the `os` fact properly without `lsb-release` installed, so I've updated this to still install that package for acceptance tests, so that testing on Puppets <7 still works, and updated the readme to note that it's not needed with Puppet 7.

I didn't figure out how to stop using `osfamily` in the `apt_*` custom facts and the `apt_key` provider. Not sure if that is even necessary.

There are a few other minor fixes in this PR, in individual commits for easier review.

### CODE REVIEW

**Comment by kenyon** [comment]
I don't see why code coverage would change. :man_shrugging:

**Comment by bastelfreak** [comment]
@kenyon I raised https://tickets.puppetlabs.com/browse/FACT-2906 to get lsb packages as dependency added

**Comment by kenyon** [comment]
:hammer_and_wrench: rebased :tornado:

**Comment by carabasdaniel** [comment]
Hi @kenyon,

This PR looks great, but can you please squash the commits and then I'll merge it.

Thanks

**Comment by kenyon** [comment]
> Hi @kenyon,
> 
> This PR looks great, but can you please squash the commits and then I'll merge it.
> 
> Thanks

Thanks. I did some squashing. I think the remaining commits stand on their own.

**Comment by carabasdaniel** [comment]
Hi @kenyon,

Thanks for your contribution, looks great! 👍

**Pull request merged**
