### PR TITLE
Updated mark as title can contain dot (fixes #1074)

### LINKED ISSUE #1074: Ubuntu packages may contain dot
## Describe the Bug
```
apt::mark { 'containerd.io': setting => 'hold' }
```

## Expected Behavior
Package should be held (this is a regression)

## Steps to Reproduce
Mark any package containing a . in the package name

## Environment
 - puppet-agent  6.28.0-1jammy
 - Ubuntu 22.04

## Additional Context
there are some other packages with a . in the name.

### PR DESCRIPTION
**Pull request by xepa**
ubuntu packages can contain dots in the name, like: containerd.io

### CODE REVIEW

**Review by kenyon — DISMISSED** [review]
Fixes commit eed10ea359d0fe144da90a8425cd14dc3c6c8f18 and issue #1074.

**Review by kenyon — APPROVED** [review]

**Comment by LukasAud** [comment]
Hi @xepa, sorry for the delay in feedback. It looks like your bugfix is not passing some of our unit tests. This needs to be addressed before we can merge your PR.

**Comment by xepa** [comment]
> Hi @xepa, sorry for the delay in feedback. It looks like your bugfix is not passing some of our unit tests. This needs to be addressed before we can merge your PR.

Ah I noticed also .. seems that there are some tests that use invalid debian package names and they are expected to succeed .. (for instance the tests assume that **my_source** is a valid package name according to the [manual](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-source) its not valid)

**Comment by xepa** [comment]
Hi @LukasAud I reread the policy and found some edge cases not covered before (updated regex again) and updated the unit tests, they should now all pass.

**Review by LukasAud — APPROVED** [review]
LGTM. Thanks for your contribution.

**Pull request merged**
