### PR TITLE
Fix apt_key tempfile race condition

### PR DESCRIPTION
**Pull request by dvorak**
The Ruby Tempfile class has a finalizer that removes the file when the
GC runs.  It's not predictible when the GC will run, so you have to
ensure that the instance of the class stays in scope for as long as you
need it.

Unfortunately the tempfile method is returning just the filename of the
temporary file, which means it goes out of scope when that method
returns.  This allows the GC to reap it at any time after return.

In both CI and production environments we've seen this race fail,
causing apt-key add to fail a small (2-3%) amount of the time.

This changes the tempfile and source_to_file methods to return the
underlying Tempfile object, pushing it up into the caller's scope.  Both
of the callers immediately use the object to get its filename and then
open the file, eliminating the race.

### CODE REVIEW

**Comment by dvorak** [comment]
This improves the situation, but is still missing something, don't merge.

**Comment by dvorak** [comment]
Ok, this should be good now.  Tested by forcing GC right before running the apt-key command and cannot reproduce now.

**Comment by daenney** [comment]
Could you squash this down into one commit please?

**Comment by dvorak** [comment]
Done

**Comment by daenney** [comment]
We have a triage tonight, I'll raise it there. There's a chance we won't actually ever release another 1.8.x version of the module though, we've essentially discontinued that line.

**Comment by tphoney** [comment]
@dvorak @daenney quite correct. APT is at 2.2.1 on the forge. we will only merge into master.

**Pull request closed without merging**
