### PR TITLE
Allow GPG key fingerprints.

### PR DESCRIPTION
**Pull request by rfkrocktk**
Patch to allow GPG key fingerprints as key values.

### CODE REVIEW

**Comment by cyberious** [comment]
This will not be idempotent yet as the apt_key will always base the match on the short key.  The aforementioned shortname was removed at https://github.com/puppetlabs/puppetlabs-apt/commit/87f3f1023cad452937d3b4c0bad84c69b442ffa1 , we should either munge the name to be the shortname or reimplement the prefetch munging.

**Comment by WolverineFan** [comment]
I think shortening the long key in 87f3f10 is bad.  That's going to lead to collisions (maybe that's what you meant).  It would be better to save all the variants and use the length to figure out which key to check.  I tried a quick hack to do that and it doesn't work the way I expected.  Maybe I'm not understanding how the prefetch method works.

**Comment by cyberious** [comment]
Prefetch has all of the keys ahead of time and can not figure out the ID length.  A possible solution is to add a property that we would read in as well for the fingerprint and upon prefetch if the id == 40 than we would match based on fingerprint rather than id/name.

**Comment by WolverineFan** [comment]
This is what I was thinking, but my Ruby (and Puppet) are not great, so maybe this can't work?

We would store each option in the apt_keys hash and use the name length to figure out which key to match on.

```ruby
   def self.prefetch(resources)
     apt_keys = instances
     resources.keys.each do |name|

     if name.length == 40
       if provider = apt_keys.find{ |key| key.fingerprint == name }
         resources[name].provider = provider
       end
     elsif name.length == 16
       if provider = apt_keys.find{ |key| key.long == name }
         resources[name].provider = provider
       end
    elsif name.length == 8
       if provider = apt_keys.find{ |key| key.short == name }
         resources[name].provider = provider
       end
       end
     end
   end
```

**Comment by cyberious** [comment]
that logic looks correct.

**Comment by cyberious** [comment]
However with that we need to add the properties for long short and fingerprint.

**Comment by WolverineFan** [comment]
I did that too:
```ruby
   def self.key_line_hash(pub_line, fpr_line)
     pub_split = pub_line.split(':')
     fpr_split = fpr_line.split(':')
 
    fingerprint = fpr_split.last
     return_hash = {
      :key_fingerprint => fingerprint,
      :key_long        => fingerprint[-16..-1], # last 16 characters of fingerprint
      :key_short       => fingerprint[-8..-1], # last 8 characters of fingerprint
```

And referenced them in the self.instances function.  Maybe some other change I made is causing the failure.  I'll do some more experimenting today if I can get the tests running locally

**Comment by rfkrocktk** [comment]
Thanks everyone for helping out on this. You're planning on adding tests to
cover this exact case, right? Getting the tests to pass is one thing, but
covering this new case is another, both are really important.

**Comment by WolverineFan** [comment]
Very true. I'm going to rebase all of this on current master and merge it all into a single commit to keep it pretty.

**Comment by rfkrocktk** [comment]
Thank you so much, it'll be nice to see this hit production :)

**Comment by WolverineFan** [comment]
Opened #404 with the new tests and bug fixes

**Comment by daenney** [comment]
I'm going to close this in favour of #404.

**Pull request closed without merging**
