### PR TITLE
Add ability to specify a hash of apt::conf defines

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@tphoney could you take a look please

**Comment by daenney** [comment]
Seems good to me 😄

**Comment by tphoney** [comment]
@ghoneycutt we need a docs update. Thanks for the change !

**Comment by ghoneycutt** [comment]
@tphoney @daenney 

I've added the README entry. Could you please merge? Thanks!

**Comment by daenney** [comment]
Thanks @ghoneycutt!

**Comment by ghoneycutt** [comment]
Thank you @daenney !

Could you please tag a new release.

**Pull request merged**
