### PR TITLE
(MODULES-8081): add support for hkps:// protocol in apt::key

### PR DESCRIPTION
**Pull request by simondeziel**
Add hkps:// to the list of protocols supported by apt::key
(hkp://, http:// and https://).

### CODE REVIEW

**Comment by simondeziel** [comment]
https://travis-ci.org/puppetlabs/puppetlabs-apt/jobs/439464775 and https://travis-ci.org/puppetlabs/puppetlabs-apt/jobs/439464776 are failing because hpks started being supported in newer Debian/Ubuntu releases. I'm not sure how to update the tests to allow hkps:// only on recent distro versions.

**Comment by david22swan** [comment]
@simondeziel I think the best thing to do in this instance is to but an exception around the test's so that their only run on the machines that support hkps, and add a note into the readme which which reflects this limitation.

**Comment by david22swan** [comment]
@simondeziel Your changes are currently failing on a syntax check, heres the test output:
```
Offenses:
spec/acceptance/apt_key_provider_spec.rb:481:1: C: Style/ConditionalAssignment: Use the return of the conditional for variable assignment and comparison.
if fact('operatingsystem') =~ %r{Ubuntu} and fact('operatingsystemrelease') =~ %r{^18\.04} ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/acceptance/apt_key_provider_spec.rb:481:42: C: Style/AndOr: Use && instead of and. (https://github.com/bbatsov/ruby-style-guide#no-and-or-or)
if fact('operatingsystem') =~ %r{Ubuntu} and fact('operatingsystemrelease') =~ %r{^18\.04}
                                         ^^^
```

**Comment by david22swan** [comment]
@simondeziel Also, the documentation in the key.pp file still need's to be updated. Everything else looks good to me though.

**Comment by simondeziel** [comment]
@david22swan, please let me know if something's missing.

**Comment by david22swan** [comment]
screen shot 2018-10-31 at 11 58 19 am

**Comment by david22swan** [comment]
@simondeziel runs clean on adhoc so i'm happy to merge. Sorry for the wait, was out on holiday.

**Pull request merged**
