### PR TITLE
Adding a new parameter for dist

### PR DESCRIPTION
**Pull request by luckyraul**
Feature for a new possibility to replace LinuxMint with Ubuntu

### CODE REVIEW

**Comment by sheenaajay** [comment]
@luckyraul Thanks for submitting the PR.
Could you please change the PR title to adding a new parameter for dist.
Also could you please fix the travis failures.

**Comment by luckyraul** [comment]
renamed.
Trigger a new build, the test fail is not related to changes

**Comment by sheenaajay** [comment]
Screen Shot 2019-12-09 at 14 25 58

**Comment by sheenaajay** [comment]
Thanks for your contribution @luckyraul

**Pull request merged**
