### PR TITLE
Change delete keys to use fingerprint instead of short or long id

### PR DESCRIPTION
**Pull request by cyberious**

### CODE REVIEW

**Comment by WolverineFan** [comment]
The issue I foresee here is that the customer manifest may specify any of the key options (short/long/fingerpint) but the delete function always uses the same thing no matter what they have specified.  That means if the customer wants to ensure a short key is absent, this version might not do that because the short key could match more than one fingerprint.

I think the code needs to be refactored to use what the customer manifest specified rather than using the provider, OR we could consider dropping support for short keys entirely (which would definitely be a major version bump)

**Comment by WolverineFan** [comment]
It suddenly occurred to me that we should also handle short key conflicts when we are matching the manifest to the provider.  I don't think that would work right (and it needs a test).

**Comment by cyberious** [comment]
I believe if they specified the short key and we delete by the fingerprint they might inadvertently delete the wrong key anyways.  We could detect if the ID is a short key and use that when short otherwise use fingerprint.

**Comment by cyberious** [comment]
@WolverineFan also after thinking about this, the conflicts of short keys will be less relevant as far as a prefetch but more so if they are using the short key and we match the first short key.  Are you suggesting we iterate over all and if there by chance two short keys with different fingerprints that we throw a warning?

**Comment by WolverineFan** [comment]
Yes, I think something like that would be good.  Issue a warning (or even an error?) if we find 2 keys matching the specified key (even a long could theoretically have a conflict, it's just less likely).  The user will almost certainly want to update their manifests when this happens.

In a way it's a shame the colliding puppetlabs key was revoked since that would have made for an excellent test case.  I'm sure there must be other short key collisions out there legitimately though.

**Comment by WolverineFan** [comment]
Found one!  http://www.asheesh.org/note/debian/short-key-ids-are-bad-news.html
```
$ gpg --keyserver pgp.mit.edu --recv-key 0x70096AD1
gpg: requesting key 70096AD1 from hkp server pgp.mit.edu
gpg: key 70096AD1: public key "Asheesh Laroia <asheesh@asheesh.org>" imported
gpg: key 70096AD1: public key "Asheesh Laroia <asheesh@asheesh.org>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 2
gpg:               imported: 2  (RSA: 1)
$ gpg --fingerprint --with-colon | grep 70096AD1
pub:-:1024:17:37E1C17570096AD1:2005-12-28:::-:Asheesh Laroia <asheesh@asheesh.org>::scESC:
fpr:::::::::D00436A90C4BD12002020A3C37E1C17570096AD1:
pub:-:4096:1:EC4B033C70096AD1:2011-03-11:::-:Asheesh Laroia <asheesh@asheesh.org>::cESCA:
fpr:::::::::97225E589D6B9E01533C485EEC4B033C70096AD1:
```

**Comment by mhaskel** [comment]
Closing, leaving a ticket for future work to get into 2.x https://tickets.puppetlabs.com/browse/MODULES-1661

**Pull request closed without merging**
