### PR TITLE
Allow URI escaping in any user/pass in the URL

### PR DESCRIPTION
**Pull request by dkrand**
One of my providers distributes packages from behind a password protected repository. And email addresses have become very common usernames, and the '@' in a username won't work since the URL decoder will detect that as the end of the user:pass part. This trivial patch allows both the username and the password to be URI encoded.

I'm pretty sure that doing the URI un-escaping after splitting 'parsed_value' is the right thing, in case either includes a colon ':' character.

### CODE REVIEW

**Comment by eimlav** [comment]
Hey @dkrand . Would it be possible to add some tests to verify that this is working as intended? Cheers.

**Comment by sheenaajay** [comment]
@dkrand Thanks for submitting the PR. Did you get a chance to add tests to verify the same. Please let us know if you need any information or help. Thank you.

**Comment by dkrand** [comment]
On 9/11/19 6:12 AM, sheenaajay wrote:
> @dkrand <https://github.com/dkrand> Thanks for submitting the PR. Did 
> you get a chance to add tests to verify the same. Please let us know if 
> you need any information or help. Thank you.

No, I haven't. I've not built any Puppet or Ruby tests before, and I 
haven't yet had the time to dig into them. Sorry.

**Comment by sheenaajay** [comment]
@dkrand we can add tests here in this section.
https://github.com/puppetlabs/puppetlabs-apt/blob/d2ae49f7e9cd344730bdb8b4071a84488577a78e/spec/unit/puppet/provider/apt_key_spec.rb#L102

We can help you to create the tests. Thank you.

**Comment by sheenaajay** [comment]
@dkrand Could you please rebase with the master so we can the tests in litmus. This module is ported to litmus now. Thank you.

**Comment by lionce** [comment]
Hello @dkrand ,

I've rebased your branch with master in order to include the latest changes from master. 

Cheers!

**Comment by michaeltlombardi** [comment]
@dkrand please do let us know if you need any help writing tests to cover this awesome patch!

**Comment by david22swan** [comment]
@dkrand In order to help you get this merged I have rebased your work onto the master and added a pair of acceptance tests. Unfortunately I ran into a problem on the way as although your change works for most special characters, it errors out when a '@' is given, likely due to it's use in clarifying the use of a password  as a divider between the username:password and the url, i.e. dummyuser:dummypassword@apt.puppetlabs.com/.......

**Comment by sheenaajay** [comment]
Thanks, @dkrand dor submitting the PR. Since there hasn't seen any activity for 3 months we are going to go ahead and close this pull request for the time being. Please feel free to re-open this pull request at any time.

**Pull request closed without merging**
