### PR TITLE
Use Debian's new official mirrors redirector

### PR DESCRIPTION
**Pull request by raoulbhatia**
See https://www.debian.org/News/weekly/2015/05/#httpredir

### CODE REVIEW

**Comment by daenney** [comment]
Did anyone actually try those links? All I get is 404s.

**Comment by raoulbhatia** [comment]
@daenney If you just click the URLs, it will yield a 404. This is an intended behavior of http://httpredir.debian.org.

The reason is, that this URL will never be accessed by `apt-get`,
see `sudo apt-get -o "Debug::Acquire::http=true" update 2>&1|grep ^GET`

There you will see, that it will actually fetch files from i.e.
http://httpredir.debian.org/debian/dists/jessie-backports/ - and this works perfectly fine.

Thanks,
Raoul

**Comment by daenney** [comment]
I'm aware of that, however last night the redir service was just throwing 404s for everything. Applying your changes caused my machines to not be able to correctly update apt. That appears to have been gremlins in the tubes though because it works correctly.

**Comment by raoulbhatia** [comment]
So, any obstacles left for getting this merged?

Thanks,
Raoul

**Pull request merged**
